notifications:
  email: false
git:
  depth: 1
env:
  global:
  - TERM=dumb
language: java
jdk: openjdk8
addons:
  apt:
    update: true
    packages:
    - bash
    - curl
    - jq
install: true
before_install:
- sudo apt-get install -yqq --no-install-suggests --no-install-recommends
  tree jq python-pip curl bash sudo >/dev/null
#
- sudo pip install --upgrade httpie >/dev/null 2>&1
#
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
- stop_any 8080 3000 80 >/dev/null
script:
- export root=$(pwd)
#
- ./gradlew >/dev/null
- java -jar -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005 -Djava.net.preferIPv4Stack=true ./build/*-microbundle.jar &
- wait_for 8080
- sleep 15
- http :8080
- http :8080/v1 string=one
- http :8080/v1 string=two
- http :8080/v1 string=three
- http :8080/v1
- stop_any 80 8080
#
- ./mvnw >/dev/null
- ./mvnw -Pbundle
- java -jar -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005 -Djava.net.preferIPv4Stack=true ./target/*-microbundle.jar &
- wait_for 8080
- sleep 15
- http :8080/v1 string=one
- http :8080/v1 string=two
- http :8080/v1 string=three
- http :8080/v1 | jq '.'
- http :8080
- stop_any 80 8080
cache:
  directories:
    - ~/.gradle
    - ~/.m2
  packages: true
  pip: true
