notifications:
  email: false
git:
  quiet: true
  depth: false
language: java
jdk: openjdk8
node_js: lts/*
python: 3.7
os: linux
arch: amd64
addons:
  apt:
    update: true
    packages:
      - wget
      - curl
      - sudo
      - lsof
      - python3-pip
install: true
before_install:
  #- export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - |
    if [ ! -f ${HOME}/.local/daggerok/bash-functions/master/main.bash ] ; then
      mkdir -p ${HOME}/.local/daggerok/bash-functions/master ;
      curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash > ${HOME}/.local/daggerok/bash-functions/master/main.bash ;
    fi
    source ${HOME}/.local/daggerok/bash-functions/master/main.bash ;
  - stop_any 80 8001 8002 8080 5432
  #
  - export PATH=$HOME/.local/bin:$PATH
  - pip3 install --user --upgrade pip setuptools
  - pip install --user --upgrade httpie
  - export root=$(pwd)
jobs:
  include:
    - stage: test
      jdk: openjdk8
      name: gradle (openjdk8)
      script:
        - ./gradlew
        - java -jar -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005
                    -Djava.net.preferIPv4Stack=true
                      ./build/libs/*-microbundle.jar &
        - wait_for 8080
        - sleep 30
        - http :8080
        - http :8080/v1 string=one
        - http :8080/v1 string=two
        - http :8080/v1 string=three
        - http :8080/v1
        - http :8080/v1/people name=ololo
        - http :8080/v1/people name=trololo
        - http :8080/v1/people/2
        - http :8080/v1/people
        - stop_any 80 8080
    - stage: test
      jdk: openjdk11
      name: gradle (openjdk11)
      script:
        - ./gradlew
        - java --add-modules java.se
               --add-exports java.base/jdk.internal.ref=ALL-UNNAMED
               --add-opens java.base/java.lang=ALL-UNNAMED
               --add-opens java.base/java.nio=ALL-UNNAMED
               --add-opens java.base/sun.nio.ch=ALL-UNNAMED
               --add-opens java.management/sun.management=ALL-UNNAMED
               --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED
               --add-opens java.base/jdk.internal.loader=ALL-UNNAMED
               --add-opens jdk.zipfs/jdk.nio.zipfs=ALL-UNNAMED
                  -jar -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005
                       -Djava.net.preferIPv4Stack=true
                         ./build/libs/*-microbundle.jar &
        - wait_for 8080
        - sleep 30
        - http :8080
        - http :8080/v1 string=one
        - http :8080/v1 string=two
        - http :8080/v1 string=three
        - http :8080/v1
        - http :8080/v1/people name=ololo
        - http :8080/v1/people name=trololo
        - http :8080/v1/people/2
        - http :8080/v1/people
        - stop_any 80 8080
    - stage: test
      jdk: openjdk8
      name: maven (openjdk8)
      script:
        - ./mvnw
        - ./mvnw -Pbundle
        - java -jar -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005
                    -Djava.net.preferIPv4Stack=true
                      ./target/*-microbundle.jar &
        - wait_for 8080
        - sleep 30
        - http :8080/v1 string=one
        - http :8080/v1 string=two
        - http :8080/v1 string=three
        - http :8080/v1
        - http :8080
        - http :8080/v1/people name=ololo
        - http :8080/v1/people name=trololo
        - http :8080/v1/people/2
        - http :8080/v1/people
        - stop_any 80 8080
    - stage: test
      jdk: openjdk11
      name: maven (openjdk11)
      script:
        - ./mvnw
        - ./mvnw -Pbundle
        - java --add-modules java.se
               --add-exports java.base/jdk.internal.ref=ALL-UNNAMED
               --add-opens java.base/java.lang=ALL-UNNAMED
               --add-opens java.base/java.nio=ALL-UNNAMED
               --add-opens java.base/sun.nio.ch=ALL-UNNAMED
               --add-opens java.management/sun.management=ALL-UNNAMED
               --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED
               --add-opens java.base/jdk.internal.loader=ALL-UNNAMED
               --add-opens jdk.zipfs/jdk.nio.zipfs=ALL-UNNAMED
                  -jar -Xdebug
                       -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005
                       -Djava.net.preferIPv4Stack=true
                         ./target/*-microbundle.jar &
        - wait_for 8080
        - sleep 30
        - http :8080/v1 string=one
        - http :8080/v1 string=two
        - http :8080/v1 string=three
        - http :8080/v1
        - http :8080
        - http :8080/v1/people name=ololo
        - http :8080/v1/people name=trololo
        - http :8080/v1/people/2
        - http :8080/v1/people
        - stop_any 80 8080
    - stage: test
      jdk: openjdk11
      name: gradle updates (openjdk11)
      script: ./gradlew dependencyUpdates -Drevision=release
    - stage: test
      jdk: openjdk8
      name: gradle updates
      script: ./gradlew dependencyUpdates -Drevision=release
    - stage: test
      jdk: openjdk11
      name: maven updates (openjdk11)
      script: ./mvnw versions:display-property-updates
    - stage: test
      jdk: openjdk8
      name: maven updates
      script: ./mvnw versions:display-property-updates
before_cache:
  - find ~/.gradle -name "fileHashes.bin" -print0 | xargs -0 rm -rfv '{}'
  - for item in $(find ~/.gradle -name "*.lock") ; do rm -rfv $item ; done
cache:
  pip: true
  packages: true
  directories:
    - ~/.local/daggerok
    - ~/.gradle
    - ~/.m2
