dist: xenial
notifications:
  email: false
git:
  quiet: true
  depth: 1
language: java
jdk: openjdk8
node_js: lts/*
python: 3
addons:
  apt:
    update: true
    packages:
      - tree
      - sudo
      - lsof
      - wget
      - bash
      - curl
      - jq
      - libxml2-utils
      - unzip
      - python3-dev
      - python3-pip
      - python3-six
      - python3-setuptools
install: true
before_install:
  - docker-compose -v
  - export PATH=$HOME/.local/bin:$PATH
  - pip3 install --user $(whoami) --upgrade pip >/dev/null # pip3 -> pip
  - pip install --user $(whoami) --upgrade httpie >/dev/null 2>&1
  - http --version --debug
  #
  - source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
  - stop_any 80 8080 3000 >/dev/null
script:
  - export root=$(pwd)
  #
  - ./gradlew >/dev/null
  - java -jar -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005 -Djava.net.preferIPv4Stack=true ./build/*-microbundle.jar &
  - wait_for 8080
  - sleep 30
  - http :8080
  - http :8080/v1 string=one
  - http :8080/v1 string=two
  - http :8080/v1 string=three
  - http :8080/v1
  - stop_any 80 8080
  #
  - ./mvnw >/dev/null
  - ./mvnw -Pbundle
  - java -jar -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005 -Djava.net.preferIPv4Stack=true ./target/*-microbundle.jar &
  - wait_for 8080
  - sleep 30
  - http :8080/v1 string=one
  - http :8080/v1 string=two
  - http :8080/v1 string=three
  - http :8080/v1
  - http :8080
  - stop_any 80 8080
cache:
  pip: true
  packages: true
  directories:
    - ~/.gradle
    - ~/.m2
